generate:
	python3 init-scripts/Production-Ready-generator.py

up: generate
	docker-compose -f docker-compose.generated.yml up --build

down:
	docker-compose -f docker-compose.generated.yml down -v

show:
	make generate
	cat docker-compose.generated.yml
